# Generated by Django 4.2.5 on 2023-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="new", max_length=100),
            preserve_default=False,
        ),
    ]
